version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    working_dir: /app
    expose:
      - 8080
    env_file:
      - ./settings/.env

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - backend
