cloud:
  aws:
    credentials:
      secret-key: ${AWS_CREDENTIALS_SECRET_KEY}
      access-key: ${AWS_CREDENTIALS_ACCESS_KEY}
    s3:
      bucket: ${AWS_CREDENTIALS_BUCKET}
    region:
      static: ${AWS_CREDENTIALS_REGION}
    stack:
      auto: 'false'
spring:
  jpa:
    generate-ddl: 'false'
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        enable_lazy_load_no_trans: 'true'
        format_sql: 'false'
    database: mysql
  profiles:
    include: oauth
  datasource:
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME}
    password: ${DATASOURCE_USER_PASSWORD}
    username: ${DATASOURCE_USER_NAME}
    url: ${DATASOURCE_URI}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  config:
    activate:
      on-profile: prod
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
app:
  oauth2:
    authorizedRedirectUris: ${AUTHORIZED_REDIRECT_URIS}
    defaultRedirectUri: ${DEFAULT_REDIRECT_URIS}
  auth:
    refreshTokenExpiry: '604800000'
    tokenSecret: ${AUTH_TOKEN_SECRET_KEY}
    tokenExpiry: '1800000'
cors:
  allowed-origins: '*'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: '3600'
'---': ''
application:
  version: 1.0.0
  title: e-weather
jwt:
  secret: ${JWT_SECRET_KEY}
