application:
  version: 1.0.0
  title: e-weather

server:
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    jpa:
      repositories:
        bootstrap-mode: default

  datasource:
    url: jdbc:h2:mem:testdb # Set the database URL a constant

  h2:
    console:
      enabled: true # Enable H2 console
      settings:
        web-allow-others: true # Allow H2 console access from browser

  jpa:
    show-sql: true # Show SQL generated

  profiles:
    include: oauth
  security:
    oauth2:
      client:
        registration:
          google:
            client-secret: ${CLIENT_SECRET_KEY}
            client-id: ${CLIENT_ID}
            scope: profile, email
