application:
  version: 1.0.0
  title: eweather

cloud:
  aws:
    credentials:
      secret-key: ${AWS_S3_BUCKET_SECRET_KEY}
      access-key: ${AWS_S3_BUCKET_ACCESS_KEY}
    s3:
      bucket: ${AWS_S3_BUCKET_NAME}
    region:
      static: ap-northeast-2
    stack:
      auto: 'false'
spring:
  config:
    import:
    - optional:file:.env[.properties]
    - classpath:/application-springboot.yml
  jpa:
    generate-ddl: 'false'
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        enable_lazy_load_no_trans: 'true'
        format_sql: 'false'
    database: mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${DATABASE_PASSWORD}
    username: ${DATABASE_USER_NAME}
    url: ${DATABASE_URL}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET_KEY}
            scope: profile, email
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
app:
  oauth2:
    authorizedRedirectUris: ${AUTHORIZED_REDIRECT_URIS}
    defaultRedirectUri: ${DEFAULT_REDIRECT_URI}
  auth:
    refreshTokenExpiry: ${REFRESH_TOKEN_EXPIRY}
    tokenSecret: ${AUTH_TOKEN_SECRET}
    tokenExpiry: ${TOKEN_EXPIRY}
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}
  allowed-methods: ${CORS_ALLOWED_METHODS}
  allowed-headers: ${CORS_ALLOWED_HEADERS}
  max-age: ${CORS_MAX_AGE}
jwt:
  secret: ${JWT_SECRET}
